"""crear candidatos y postulaciones

Revision ID: 63c328468779
Revises: bb4125134268
Create Date: 2026-09-20 17:13:00.369260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c328468779'
down_revision: Union[str, Sequence[str], None] = 'bb4125134268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidatos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=254), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('github_url', sa.String(length=500), nullable=True),
    sa.Column('portafolio_url', sa.String(length=500), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_vacante', sa.Integer(), nullable=False),
    sa.Column('id_candidato', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('recibida', 'en_revision', 'preseleccionada', 'descartada', 'retirada', name='estado_postulacion', native_enum=False, create_constraint=True), server_default=sa.text("'recibida'"), nullable=False),
    sa.Column('postulado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['id_candidato'], ['candidatos.id'], ),
    sa.ForeignKeyConstraint(['id_vacante'], ['vacantes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_candidato', 'id_vacante')
    )
    op.create_index(op.f('ix_postulaciones_id_candidato'), 'postulaciones', ['id_candidato'], unique=False)
    op.create_index(op.f('ix_postulaciones_id_vacante'), 'postulaciones', ['id_vacante'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postulaciones_id_vacante'), table_name='postulaciones')
    op.drop_index(op.f('ix_postulaciones_id_candidato'), table_name='postulaciones')
    op.drop_table('postulaciones')
    op.drop_table('candidatos')
    # ### end Alembic commands ###
