"""crear tabla vacantes

Revision ID: bb4125134268
Revises: fdf5afb00003
Create Date: 2026-09-19 14:33:18.892923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb4125134268'
down_revision: Union[str, Sequence[str], None] = 'fdf5afb00003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=False),
    sa.Column('modalidad', sa.Enum('remoto', 'hibrido', 'presencial', name='modalidad_vacante', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('ubicacion', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Enum('borrador', 'publicada', 'cerrada', name='estado_vacante', native_enum=False, create_constraint=True), server_default=sa.text("'borrador'"), nullable=False),
    sa.Column('fecha_limite', sa.Date(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('sysutcdatetime()'), nullable=False),
    sa.Column('id_creador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creador'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacantes_id_creador'), 'vacantes', ['id_creador'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacantes_id_creador'), table_name='vacantes')
    op.drop_table('vacantes')
    # ### end Alembic commands ###
